### PR TITLE
Fix absolute paths

### PR DESCRIPTION
**Pull request by wayofthefuture**
Much easier to understand without the superfluous absolute paths cluttering the diagram. Have some more changes coming... Only tested on Windows, not sure how will work on Linux. Thanks.

### CODE REVIEW

**Comment by wayofthefuture** [comment]
Any word on this?

**Comment by auchenberg** [comment]
I haven't had time to review this project in a long time. Wanna help out and become a fellow owner?

**Comment by auchenberg** [comment]
👍

**Comment by wayofthefuture** [comment]
Yes sounds good

**Comment by auchenberg** [comment]
Welcome onboard! With great powers comes responsibility :)

**Pull request merged**
