### PR TITLE
-v/--reverse option allows for arrow reversal, -t allows title

### PR DESCRIPTION
**Pull request by chicagogrooves**
* [x] -v switch
* [x] -t switch 

```
# two things point to underscore
./bin/dependo -f cjs lib/ > example/index.html ; open example/index.html

# underscore points to two things
./bin/dependo -v -f cjs lib/ > example/index.html ; open example/index.html

```

### CODE REVIEW

**Comment by chicagogrooves** [comment]
The scenario this feature supports is this:

When `A` depends on `B`, the order of tasks that must be done is `B`, then `A`. So it's sometimes useful to see things in reverse order. Put another way:

> The converse of the dependency graph is the integration plan.
>     -- *Dwayne "The Rock" Johnson (I think)*

This feature supports viewing the "integration plan". But equivalently, *"reverses the arrows"* describes it just fine.

**Comment by chicagogrooves** [comment]
I believe this is ready for review now.

**Comment by auchenberg** [comment]
LGTM :+1:  I hadn't though of this functionality, so let's get it in.

**Comment by chicagogrooves** [comment]
TY! version bump and publish ?

**Comment by auchenberg** [comment]
Done.

**Comment by chicagogrooves** [comment]
ty!

**Pull request merged**
